### ISSUE TITLE
Adjustable width editor

### ISSUE THREAD

**Issue by maikuru** [maikuru/cesium#10]
As a user I should be able to expand the width of the editor to make is thinner or wider

## CoS
* Editor can be made thinner or wider
* Viewer's width adjusts accordingly.

**Comment by adi2412** [comment]
Hmm, this is going to be slightly harder. Currently I'm using bootstrap grid system for the editor and cesium frame. Assuming I stick to that, I would need to add some javascript to move between the grid blocks. Those are discrete, and won't give a continuous width adjustment. For that, I'd need to remove the grid system and add some custom javascript.

**Comment by maikuru** [comment]
This should be discussed in the forum and have the community decide.

We might just be able to have a narrow, medium and wide view option that can be toggled via a button group: http://getbootstrap.com/components/#btn-groups-single

**Comment by adi2412** [comment]
Discrete views should be ok. Should I put this up on the forum?

**Comment by maikuru** [comment]
yes.  I think that is worth mentioning, most will probably not chime in, but it's good to put out there

**Comment by maikuru** [comment]
When you resize it clears your content in the editor.  luckily it is recoverable if you do a ctrl undo, but that is a huge issue for usability

**Comment by adi2412** [comment]
Sorry about that, it was due to the state not being updated. Fixed that.

**Comment by maikuru** [comment]
When the editor is set to 'small' the viewer is wrapping to a new line when you get below a width of 1170.
