### ISSUE TITLE
Editor: Warning Messages

### ISSUE THREAD

**Issue by maikuru** [maikuru/cesium#6]
As a user I want to see javascript syntax errors and warnings as I type

## CoS
* As the user types syntax warnings appear
* As the user types syntax errors are 
* Should present same warnings/errors to the Dojo version

## Notes
Might be best if this is handled when the user goes to a new line with the active cursor. Usability is key so try immediate, as you type, and active cursor, line changing, to trigger the validation.  Get opinions from community on which is better

**Comment by adi2412** [comment]
Added in 52e308dbd98c4afeb568ba5a180e63dcdcb7ccd6

**Comment by maikuru** [comment]
Getting a 'use strict' warning.  this is probably the only warning we don't want to display.
